version: "3.8"

services:
  db:
    image: postgis/postgis
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  umap_app:
    build: ./umap
    command: gunicorn wsgi -b 0.0.0.0:8019
    env_file: .env
    volumes:
      - static_files:/static
      - media_files:/media
    depends_on:
      db:
        condition: service_healthy

  umap_web:
    build: ./nginx
    ports:
      - "$APP_PORT:80"
    depends_on:
      - umap_app
    volumes:
      - static_files:/static
      - media_files:/media

volumes:
  db_data:
  static_files:
  media_files:
