version: "3.8"

services:
  db:
    image: postgis/postgis
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  umap_app:
    build: ./umap
    command: umap runserver 0.0.0.0:8019
    env_file: .env
    volumes:
      - ./django:/code
    ports:
      - "$APP_PORT:8019"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
